#!/usr/bin/ruby

from time import sleep

print('{"PROGRESS": 0, "MESSAGE": "Beggining process...", "ERROR":0}')

sleep(5)

print('{"PROGRESS": 50, "MESSAGE": "Adding new email", "ERROR":0}')

sleep(5)

print('{"PROGRESS": 100, "MESSAGE": "Successful!!!", "ERROR":0}')


